### ISSUE TITLE
Springboot 2.4.x application failing on startup with version 1.7.0

### ISSUE THREAD

**Issue by mukundjalan** [resilience4j/resilience4j#1373]
Resilience4j version: 1.7.0

Java version: 1.8

Spring Boot Version 2.4.2

We have an application which was running fine with spring boot 2.3.x & resilience4j 1.7.0. Today I made an upgrade to Spring boot 2.4.2 and the application context is failing to load. Can you please assist on this?

I see that the method signature expected here is a bit different, do I need to add any additional configuration for this to work with spring boot 2.4.x?

```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'retryAspect' defined in class path resource [io/github/resilience4j/retry/autoconfigure/RetryConfigurationOnMissingBean.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.retry.configure.RetryAspect]: Factory method 'retryAspect' threw exception; nested exception is java.lang.NoSuchMethodError: io.github.resilience4j.retry.configure.RetryConfiguration.retryAspect(Lio/github/resilience4j/retry/configure/RetryConfigurationProperties;Lio/github/resilience4j/retry/RetryRegistry;Ljava/util/List;Lio/github/resilience4j/fallback/FallbackDecorators;Lio/github/resilience4j/spelresolver/SpelResolver;Lio/github/resilience4j/core/ContextAwareScheduledThreadPoolExecutor;)Lio/github/resilience4j/retry/configure/RetryAspect;
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:658)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1336)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1179)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:571)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.aop.aspectj.annotation.BeanFactoryAspectInstanceFactory.getOrder(BeanFactoryAspectInstanceFactory.java:139)
	at org.springframework.aop.aspectj.annotation.LazySingletonAspectInstanceFactoryDecorator.getOrder(LazySingletonAspectInstanceFactoryDecorator.java:95)
	at org.springframework.aop.aspectj.annotation.InstantiationModelAwarePointcutAdvisorImpl.getOrder(InstantiationModelAwarePointcutAdvisorImpl.java:181)
	at org.springframework.core.OrderComparator.findOrder(OrderComparator.java:145)
	at org.springframework.core.annotation.AnnotationAwareOrderComparator.findOrder(AnnotationAwareOrderComparator.java:64)
	at org.springframework.core.OrderComparator.getOrder(OrderComparator.java:128)
	at org.springframework.core.OrderComparator.getOrder(OrderComparator.java:116)
	at org.springframework.core.OrderComparator.doCompare(OrderComparator.java:86)
	at org.springframework.core.OrderComparator.compare(OrderComparator.java:73)
	at org.springframework.aop.aspectj.autoproxy.AspectJPrecedenceComparator.compare(AspectJPrecedenceComparator.java:83)
	at org.springframework.aop.aspectj.autoproxy.AspectJPrecedenceComparator.compare(AspectJPrecedenceComparator.java:51)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator$PartiallyComparableAdvisorHolder.compareTo(AspectJAwareAdvisorAutoProxyCreator.java:129)
	at org.aspectj.util.PartialOrder$SortObject.addDirectedLinks(PartialOrder.java:71)
	at org.aspectj.util.PartialOrder.addNewPartialComparable(PartialOrder.java:93)
	at org.aspectj.util.PartialOrder.sort(PartialOrder.java:129)
	at org.springframework.aop.aspectj.autoproxy.AspectJAwareAdvisorAutoProxyCreator.sortAdvisors(AspectJAwareAdvisorAutoProxyCreator.java:75)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.findEligibleAdvisors(AbstractAdvisorAutoProxyCreator.java:100)
	at org.springframework.aop.framework.autoproxy.AbstractAdvisorAutoProxyCreator.getAdvicesAndAdvisorsForBean(AbstractAdvisorAutoProxyCreator.java:78)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:337)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:289)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:444)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:609)
	... 70 more
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [io.github.resilience4j.retry.configure.RetryAspect]: Factory method 'retryAspect' threw exception; nested exception is java.lang.NoSuchMethodError: io.github.resilience4j.retry.configure.RetryConfiguration.retryAspect(Lio/github/resilience4j/retry/configure/RetryConfigurationProperties;Lio/github/resilience4j/retry/RetryRegistry;Ljava/util/List;Lio/github/resilience4j/fallback/FallbackDecorators;Lio/github/resilience4j/spelresolver/SpelResolver;Lio/github/resilience4j/core/ContextAwareScheduledThreadPoolExecutor;)Lio/github/resilience4j/retry/configure/RetryAspect;
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653)
	... 102 more
Caused by: java.lang.NoSuchMethodError: io.github.resilience4j.retry.configure.RetryConfiguration.retryAspect(Lio/github/resilience4j/retry/configure/RetryConfigurationProperties;Lio/github/resilience4j/retry/RetryRegistry;Ljava/util/List;Lio/github/resilience4j/fallback/FallbackDecorators;Lio/github/resilience4j/spelresolver/SpelResolver;Lio/github/resilience4j/core/ContextAwareScheduledThreadPoolExecutor;)Lio/github/resilience4j/retry/configure/RetryAspect;
	at io.github.resilience4j.retry.autoconfigure.AbstractRetryConfigurationOnMissingBean.retryAspect(AbstractRetryConfigurationOnMissingBean.java:104)
	at io.github.resilience4j.retry.autoconfigure.RetryConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$f66e2a84.CGLIB$retryAspect$2(<generated>)
	at io.github.resilience4j.retry.autoconfigure.RetryConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$f66e2a84$$FastClassBySpringCGLIB$$d45ab09b.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at io.github.resilience4j.retry.autoconfigure.RetryConfigurationOnMissingBean$$EnhancerBySpringCGLIB$$f66e2a84.retryAspect(<generated>)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	... 103 more

```

**Comment by Romeh** [comment]
@mukundjalan  please check https://github.com/resilience4j/resilience4j/issues/1361

**Comment by mukundjalan** [comment]
@Romeh that was indeed the issue in my case, spring boot was importing 1.6.1 related dependencies and I had 1.7.0. I could solve it by including the suggested BOM. Although it is necessary that the BOM is included in the pom before the spring boot starters otherwise spring boot would take precedence. Thanks for helping me solve this issue.
