### ISSUE TITLE
Explicit SemVer support

### ISSUE THREAD

**Issue by dagguh** [resilience4j/resilience4j#1278]
Related to https://github.com/resilience4j/resilience4j/issues/266#issuecomment-479458408

It'd be awesome if the lib would follow [SemVer](https://semver.org/spec/v2.0.0.html). It's not about avoiding breaking compat, but communicating that clearly with the version itself. Note that the first rule of SemVer is declaring what is the public API. As a lib consumer I would then know what I can rely on. It's also interesting to see if/how binary and behavioral compat is included.

**Comment by dagguh** [comment]
As a lib consumer, SemVer is useful when I have to fix a transitive dependency conflict. If my deps conflict on `resilience4j` 1.5.0 and 1.6.1 then I know I can force the 1.6.1 version, because it's backwards compatible. I'd also know I couldn't choose 1.5.0, because 1.6.0 has more API.

Such bogus conflicts would be even automated away by depending on a version range. For example `[1.6.0, 2.0.0)` means "I need API from 1.6.0, but I won't work with 2.0.0 breaking changes".

If the conflict is between 1.4.0 and 2.0.0 then I know they are incompatible. Then I'd have to hunt for other dep versions or ask dep authors to migrate to 2.x.y.

**Comment by sagebind** [comment]
Maybe slightly off topic, but still relevant: If you do decide to explicitly follow semver, I recommend applying semver to your binary API and not just your source-code API. Please read [this article](http://codefhtagn.blogspot.com/2010/11/java-binary-compatibility-more-than.html) for an explanation of what binary compatibility means in Java if you don't know, but essentially what it means is that you do not need to recompile an application or library in order to upgrade compatible versions.

I noticed today that resilience4j-retry version 1.2.0 broke binary compatibility with 1.1.0. Specifically, `RetryConfig.Builder#intervalFunction` was changed to accept a more general `io.github.resilience4j.core.IntervalFunction` interface instead of the retry-specific `io.github.resilience4j.retry.IntervalFunction` interface (which extends the former). While this change was backwards-compatible from a source-code perspective, `intervalFunction(io.github.resilience4j.core.IntervalFunction)` and `intervalFunction(io.github.resilience4j.retry.IntervalFunction)` are completely different methods from the JVM's perspective, even though the former is a more general form of the latter. After upgrading, at runtime we got these errors:

```
java.lang.NoSuchMethodError: io.github.resilience4j.retry.RetryConfig$Builder.intervalFunction(Lio/github/resilience4j/retry/IntervalFunction;)Lio/github/resilience4j/retry/RetryConfig$Builder;
```

unless we recompiled everything referencing `RetryConfig`. This is just a tip to watch out for this sort of problem when you are trying to maintain compatibility in a library.

**Comment by RobWin** [comment]
Thx

**Comment by dagguh** [comment]
I found these [OpenJDK compatibility notes](http://cr.openjdk.java.net/~darcy/OpenJdkDevGuide/OpenJdkDevelopersGuide.v0.777.html#binary_compatibility) useful when declaring and maintaining our SemVer libs.
